# Generated by Django 5.0.1 on 2024-04-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_product_stock_alter_category_id_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
