# Generated by Django 5.0.1 on 2024-04-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_birthday',
        ),
    ]
