# Generated by Django 5.0.1 on 2024-04-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_client_date_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
    ]
