# Generated by Django 5.0.1 on 2024-04-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
