# Generated by Django 5.0.1 on 2024-04-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_product_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_service',
        ),
    ]
