# Generated by Django 5.0.1 on 2024-04-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_sale_date_end_alter_detsale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
