# Generated by Django 5.0.1 on 2024-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_product_is_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnisp', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('namessp', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnamessp', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('addresssp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('emailsp', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone_numbersp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Es servicio'),
        ),
    ]
