# Generated by Django 5.0.1 on 2024-05-02 15:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_paymentform_payment_payment_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_form',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de Crédito'), ('TB', 'Transferencia Bancaria')], max_length=2, null=True),
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='pagos',
            field=models.ManyToManyField(related_name='ventas', to='erp.payment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIALLY_PAID', 'Parcialmente Pagado'), ('PAID', 'Pagado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
        ),
        migrations.DeleteModel(
            name='PaymentForm',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
