# Generated by Django 5.0.1 on 2024-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_remove_payment_payment_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_form',
            field=models.CharField(blank=True, choices=[('CNT', 'Contado'), ('CRD', 'Crédito')], max_length=3, null=True),
        ),
    ]
