# Generated by Django 5.0.1 on 2024-05-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_payment_payment_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sale',
            new_name='sale_id',
        ),
    ]
