# Generated by Django 5.0.1 on 2024-05-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_rename_sale_payment_sale_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='pagos',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_form',
            field=models.CharField(blank=True, choices=[('CNT', 'Contado'), ('CRD', 'Credito')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de crédito')], max_length=2, null=True),
        ),
    ]
