# Generated by Django 5.0.1 on 2024-05-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_rename_sale_id_payment_sale_remove_sale_pagos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
