# Generated by Django 5.0.1 on 2024-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('NQ', 'Nequi')], max_length=2, null=True),
        ),
    ]
