# Generated by Django 5.0.1 on 2024-05-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_remove_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Alidatmiento', 'Alidatmiento'), ('Preparación', 'Preparación'), ('Laboratorio', 'Laboratorio'), ('Revisión', 'Revisión'), ('Entrega', 'Entrega')], max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('det_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='erp.detsale')),
            ],
            options={
                'verbose_name': 'Fase de Producto',
                'verbose_name_plural': 'Fases de Productos',
                'ordering': ['id'],
            },
        ),
    ]
