# Generated by Django 5.0.1 on 2024-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_productphase_options_alter_product_is_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('NQ', 'Nequi'), ('QR', 'QR')], max_length=2, null=True),
        ),
    ]
